[build]
  command = "npm install"
  publish = "public"

[build.environment]
  ADMIN_PASSWORD = "your_secure_password"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true